sonar.projectKey=payments-portal
sonar.organization=shatzgp
sonar.sources=backend
sonar.exclusions=backend/node_modules/**,backend/test/**,frontend/**
sonar.tests=backend/test
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info